<a href="https://colab.research.google.com/github/MartaPCastillo/Simulacion-II/blob/main/Prueba%20de%20Bondad%20de%20Ajuste.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prueba de bondad de ajuste

In [76]:
import numpy as np

#Solicitamos la cantidad de clases y el total de observaciones en la muestra
n = input('Número de clases: ')
n = int (n)
T = input('Total de observaciones: ')
T = int(T)

#Calculamos la frecuencia esperada en cada clase
E = int(T/n)
print ("Frecuencia esperada en la clase i es: ", E)

#iniciamos y definimos un contador e inciamos la variable suma
contador = 0
contador = int(contador)

suma=0

#definimos una lista vacia
lista=[]
#disponemos un ciclo de n vueltas
for i in range(n):
    O = input("Frecuencia observada en la clase" + str(contador + 1) + ": ")
    O = int(O)
    lista.append(O)
    contador += 1
    #indicamos como se realizará la suma
    suma = suma + O

#imprimimos la lista y la suma
print(lista)
print("La suma de las frecuencias observadas es:", suma)

#hacemos un array con la lista para restarle a cada valor la frecuencia esperada
a = np.array([lista])
a = a - E
#imprimimos los valores resultantes de la resta
print(a)
#hacemos un array con la lista para elevar cada valor al cuadrado
b = np.array([a])
b = b ** 2
#imprimimos los valores al cuadrado
print(b)
#hacemos un array con la lista para dividir cada valor entre la frecuencia esperada
c = np.array([b])
c = b / E
#imprimimos los resultados de cada división
print(c)
#hacemos la suma de todos los resultados de la división
suma1 = np.append(c, np.sum(c))
#imprimimos el valor de Ji cuadrada
print("El valor de X^2_c es:", np.sum(c))
#Evaluamos, tomando n-1 grados de libertad, y suponiendo que este código siempre será para n = 5, que nuestro valor de Ji cuadrada_c sea menor a 9.48 (valor de Ji cuadrada en la tabla) y obtenemos la conclusión
if np.sum(c) < 9.48:
  print ("Conclusión: No se rechaza H_0. Los valores de la muestra provienen de una distribución uniforme")
else:
  print ("Conclusión: Se rechaza H_0. Los valores de la muestra no provienen una distribución uniforme")

Número de clases: 5
Total de observaciones: 50
Frecuencia esperada en la clase i es:  10
Frecuencia observada en la clase1: 6
Frecuencia observada en la clase2: 12
Frecuencia observada en la clase3: 13
Frecuencia observada en la clase4: 7
Frecuencia observada en la clase5: 12
[6, 12, 13, 7, 12]
La suma de las frecuencias observadas es: 50
[[-4  2  3 -3  2]]
[[[16  4  9  9  4]]]
[[[1.6 0.4 0.9 0.9 0.4]]]
El valor de X^2_c es: 4.2
No se rechaza H_0. Los valores de la muestra provienen de una distribución uniforme


In [57]:


#definimos una lista vacia
lista=[]
#disponemos un ciclo de 5 vueltas
for x in range(5):
    valor=int(input("Ingrese un valor entero:"))
    lista.append(valor)

#imprimimos la lista
print(lista)

E = 10
a = np.array([lista])
a = a - E
print(a)

Ingrese un valor entero:6
Ingrese un valor entero:12
Ingrese un valor entero:13
Ingrese un valor entero:7
Ingrese un valor entero:12
[6, 12, 13, 7, 12]
[[-4  2  3 -3  2]]


In [ ]:
import openpyxl

wb = openpyxl.load_workbook('/content/Ejercicio 3.xlsx')

print(wb.sheetnames)


['Datos Ejercicio 3']


In [ ]:
import pandas as pd
import numpy as np

datos = pd.read_excel (io = '/content/Ejercicio 3.xlsx',
                         header = 0, names = None, index_col = None,
                         engine = 'openpyxl')


print(datos.sort_values(by=['Unnamed: 0','Unnamed: 1'], ascending = [True, True]))
df = pd.DataFrame(np.sort(datos.values, axis = 0), index = datos.index, columns = datos.columns)
print (df)

   Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
2           7          50           5          91          77          18   
0          38          33          25           5          69          35   
1          50          46          95          42          49          11   
3          91          36          48          88          52          76   

   Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  
2          21           4          17          62  
0          98          52          12          79  
1          78          34           2          43  
3          99          73          82          90  
   Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0           7          33           5           5          49          11   
1          38          36          25          42          52          18   
2          50          46          48          88          69          35   
3          91          50          95         